"""Dated data snapshots for reproducible real-data runs.

A live `--real` pull is not reproducible: Yahoo revises history, FRED restricts or
renames series (we hit exactly this with the ICE BofA HY series), and "today" moves.
A snapshot freezes a bundle to disk as plain CSVs plus a manifest recording the
vintage date, so a research note's numbers can be regenerated byte-for-byte later,
which is the whole point of a point-in-time framework.

CSV (not pickle) on purpose: it is human-readable and diffable in git, so a data
change is visible in review rather than an opaque binary churn.
"""
from __future__ import annotations

import datetime as _dt
import json
import os

import pandas as pd

from .panel import PriceHistory, MacroHistory, DataBundle

_PRICES = "prices.csv"
_CARRY = "carry.csv"
_MACRO = "macro.csv"
_MANIFEST = "manifest.json"


def save_snapshot(bundle: DataBundle, path: str, vintage: str | None = None) -> str:
    """Write a bundle to `path` as CSVs + manifest.json. Returns the manifest path."""
    os.makedirs(path, exist_ok=True)
    bundle.prices.raw_copy().to_csv(os.path.join(path, _PRICES))
    if bundle.carry is not None:
        bundle.carry.raw_copy().to_csv(os.path.join(path, _CARRY))
    if bundle.macro is not None:
        bundle.macro.raw_copy().to_csv(os.path.join(path, _MACRO))
    manifest = {
        "vintage": vintage or _dt.date.today().isoformat(),
        "release_lag": bundle.macro.release_lag if bundle.macro is not None else None,
        "has_carry": bundle.carry is not None,
        "has_macro": bundle.macro is not None,
        "assets": bundle.assets,
        "n_months": len(bundle.dates),
    }
    manifest_path = os.path.join(path, _MANIFEST)
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
    return manifest_path


def _read_frame(path: str) -> pd.DataFrame:
    return pd.read_csv(path, index_col=0, parse_dates=True)


def load_snapshot(path: str) -> DataBundle:
    """Rebuild a DataBundle from a snapshot directory written by save_snapshot."""
    with open(os.path.join(path, _MANIFEST)) as f:
        manifest = json.load(f)
    prices = PriceHistory(_read_frame(os.path.join(path, _PRICES)))
    carry = macro = None
    if manifest.get("has_carry"):
        carry = PriceHistory(_read_frame(os.path.join(path, _CARRY)))
    if manifest.get("has_macro"):
        macro = MacroHistory(_read_frame(os.path.join(path, _MACRO)),
                             release_lag=manifest.get("release_lag") or 1)
    return DataBundle(prices=prices, carry=carry, macro=macro)
